# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lists.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui, QtWidgets

class Ui_frmSpeciesList(object):
    def setupUi(self, frmSpeciesList):
        frmSpeciesList.setObjectName("frmSpeciesList")
        frmSpeciesList.resize(800, 486)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmSpeciesList.sizePolicy().hasHeightForWidth())
        frmSpeciesList.setSizePolicy(sizePolicy)
        frmSpeciesList.setMinimumSize(QtCore.QSize(200, 300))
        frmSpeciesList.setSizeIncrement(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_bird_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmSpeciesList.setWindowIcon(icon)
        self.scrollArea = QtWidgets.QScrollArea(frmSpeciesList)
        self.scrollArea.setGeometry(QtCore.QRect(0, 23, 671, 480))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.layLists = QtWidgets.QWidget()
        self.layLists.setGeometry(QtCore.QRect(0, 0, 657, 492))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layLists.sizePolicy().hasHeightForWidth())
        self.layLists.setSizePolicy(sizePolicy)
        self.layLists.setObjectName("layLists")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layLists)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblLocation = QtWidgets.QLabel(self.layLists)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.lblLocation.setFont(font)
        self.lblLocation.setWordWrap(True)
        self.lblLocation.setObjectName("lblLocation")
        self.verticalLayout_2.addWidget(self.lblLocation)
        self.frmRow2 = QtWidgets.QFrame(self.layLists)
        self.frmRow2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frmRow2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frmRow2.setLineWidth(0)
        self.frmRow2.setObjectName("frmRow2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frmRow2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frmRangeAndDetails = QtWidgets.QFrame(self.frmRow2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmRangeAndDetails.sizePolicy().hasHeightForWidth())
        self.frmRangeAndDetails.setSizePolicy(sizePolicy)
        self.frmRangeAndDetails.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frmRangeAndDetails.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frmRangeAndDetails.setLineWidth(0)
        self.frmRangeAndDetails.setObjectName("frmRangeAndDetails")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frmRangeAndDetails)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblDateRange = QtWidgets.QLabel(self.frmRangeAndDetails)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(QtGui.QFont.Weight.Normal)
        self.lblDateRange.setFont(font)
        self.lblDateRange.setLineWidth(0)
        self.lblDateRange.setObjectName("lblDateRange")
        self.verticalLayout.addWidget(self.lblDateRange)
        self.lblDetails = QtWidgets.QLabel(self.frmRangeAndDetails)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(QtGui.QFont.Weight.Normal)
        self.lblDetails.setFont(font)
        self.lblDetails.setLineWidth(0)
        self.lblDetails.setObjectName("lblDetails")
        self.verticalLayout.addWidget(self.lblDetails)
        self.horizontalLayout.addWidget(self.frmRangeAndDetails)
        self.frmButtons = QtWidgets.QFrame(self.frmRow2)
        self.frmButtons.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frmButtons.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frmButtons.setLineWidth(0)
        self.frmButtons.setObjectName("frmButtons")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frmButtons)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 2)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnEbird = QtWidgets.QPushButton(self.frmButtons)
        self.btnEbird.setObjectName("btnEbird")
        self.verticalLayout_3.addWidget(self.btnEbird)
        self.btnShowLocation = QtWidgets.QPushButton(self.frmButtons)
        self.btnShowLocation.setStatusTip("")
        self.btnShowLocation.setObjectName("btnShowLocation")
        self.verticalLayout_3.addWidget(self.btnShowLocation)
        self.horizontalLayout.addWidget(self.frmButtons)
        self.verticalLayout_2.addWidget(self.frmRow2)
        self.frmRow3 = QtWidgets.QFrame(self.layLists)
        self.frmRow3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frmRow3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frmRow3.setLineWidth(0)
        self.frmRow3.setObjectName("frmRow3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frmRow3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frmSpecies = QtWidgets.QFrame(self.frmRow3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.frmSpecies.setSizePolicy(sizePolicy)
        self.frmSpecies.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frmSpecies.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frmSpecies.setLineWidth(0)
        self.frmSpecies.setObjectName("frmSpecies")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frmSpecies)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblSpecies = QtWidgets.QLabel(self.frmSpecies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSpecies.setFont(font)
        self.lblSpecies.setObjectName("lblSpecies")
        self.verticalLayout_4.addWidget(self.lblSpecies)
        self.horizontalLayout_2.addWidget(self.frmSpecies)
        self.lblFind = QtWidgets.QLabel(self.frmRow3)
        self.lblFind.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFind.setObjectName("lblFind")
        self.horizontalLayout_2.addWidget(self.lblFind)
        self.txtFind = QtWidgets.QLineEdit(self.frmRow3)
        self.txtFind.setObjectName("txtFind")
        self.horizontalLayout_2.addWidget(self.txtFind)
        self.verticalLayout_2.addWidget(self.frmRow3)
        self.tblList = QtWidgets.QTableWidget(self.layLists)
        self.tblList.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tblList.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tblList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblList.setShowGrid(False)
        self.tblList.setObjectName("tblList")
        self.tblList.setColumnCount(0)
        self.tblList.setRowCount(0)
        self.tblList.horizontalHeader().setVisible(False)
        self.tblList.horizontalHeader().setHighlightSections(False)
        self.tblList.verticalHeader().setVisible(False)
        self.tblList.verticalHeader().setHighlightSections(False)
        self.verticalLayout_2.addWidget(self.tblList)
        self.txtChecklistComments = QtWidgets.QPlainTextEdit(self.layLists)
        self.txtChecklistComments.setObjectName("txtChecklistComments")
        self.verticalLayout_2.addWidget(self.txtChecklistComments)
        self.scrollArea.setWidget(self.layLists)
        self.actionSetDateFilter = QtGui.QAction(frmSpeciesList)
        self.actionSetDateFilter.setObjectName("actionSetDateFilter")
        self.actionSetLocationFilter = QtGui.QAction(frmSpeciesList)
        self.actionSetLocationFilter.setObjectName("actionSetLocationFilter")
        self.actionSetFirstDateFilter = QtGui.QAction(frmSpeciesList)
        self.actionSetFirstDateFilter.setObjectName("actionSetFirstDateFilter")
        self.actionSetLastDateFilter = QtGui.QAction(frmSpeciesList)
        self.actionSetLastDateFilter.setObjectName("actionSetLastDateFilter")
        self.actionSetSpeciesFilter = QtGui.QAction(frmSpeciesList)
        self.actionSetSpeciesFilter.setObjectName("actionSetSpeciesFilter")
        self.actionSetCountryFilter = QtGui.QAction(frmSpeciesList)
        self.actionSetCountryFilter.setObjectName("actionSetCountryFilter")
        self.actionSetStateFilter = QtGui.QAction(frmSpeciesList)
        self.actionSetStateFilter.setObjectName("actionSetStateFilter")
        self.actionSetCountyFilter = QtGui.QAction(frmSpeciesList)
        self.actionSetCountyFilter.setObjectName("actionSetCountyFilter")

        self.retranslateUi(frmSpeciesList)
        QtCore.QMetaObject.connectSlotsByName(frmSpeciesList)

    def retranslateUi(self, frmSpeciesList):
        _translate = QtCore.QCoreApplication.translate
        frmSpeciesList.setWindowTitle(_translate("frmSpeciesList", "Species Report"))
        self.lblLocation.setText(_translate("frmSpeciesList", "Location"))
        self.lblDateRange.setText(_translate("frmSpeciesList", "Date Range"))
        self.lblDetails.setText(_translate("frmSpeciesList", "Details Label"))
        self.btnEbird.setToolTip(_translate("frmSpeciesList", "Open this checklist on eBird.org."))
        self.btnEbird.setText(_translate("frmSpeciesList", "eBird"))
        self.btnShowLocation.setToolTip(_translate("frmSpeciesList", "Click to show the checklist location."))
        self.btnShowLocation.setText(_translate("frmSpeciesList", "Location"))
        self.lblSpecies.setText(_translate("frmSpeciesList", "Species"))
        self.lblFind.setText(_translate("frmSpeciesList", "Find:  "))
        self.tblList.setSortingEnabled(True)
        self.actionSetDateFilter.setText(_translate("frmSpeciesList", "Set Filter to Date"))
        self.actionSetLocationFilter.setText(_translate("frmSpeciesList", "Set Filter to Location"))
        self.actionSetFirstDateFilter.setText(_translate("frmSpeciesList", "Set Filter to \"First\" Date"))
        self.actionSetLastDateFilter.setText(_translate("frmSpeciesList", "Set Filter to \"Last\" Date"))
        self.actionSetSpeciesFilter.setText(_translate("frmSpeciesList", "Set Filter to Species"))
        self.actionSetCountryFilter.setText(_translate("frmSpeciesList", "Set Filter to Country"))
        self.actionSetStateFilter.setText(_translate("frmSpeciesList", "Set Filter to State"))
        self.actionSetCountyFilter.setText(_translate("frmSpeciesList", "Set Filter to County"))

import icons_rc
